# Generated by Django 5.0.6 on 2026-09-14 10:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('grade_type', models.CharField(choices=[('DAILY', 'Daily'), ('HOMEWORK', 'Homework'), ('QUIZ', 'Quiz'), ('QUARTER', 'Quarter'), ('EXAM', 'Exam')], default='DAILY', max_length=20)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='classes.academicyear')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='classes.quarter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
