# Generated by Django 5.0.6 on 2026-09-14 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='value',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
