# Generated by Django 5.0.6 on 2026-09-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('average_grade', models.FloatField(default=0)),
                ('attendance_percentage', models.FloatField(default=0)),
                ('homework_completion', models.FloatField(default=0, help_text='Percentage 0-100')),
                ('quiz_average', models.FloatField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
    ]
