# Generated by Django 5.0.6 on 2026-09-14 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='users.teacherprofile'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['date', 'start_time', 'end_time'], name='lessons_les_date_b72e2e_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['teacher', 'date'], name='lessons_les_teacher_4ea27b_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['room', 'date'], name='lessons_les_room_82cf02_idx'),
        ),
    ]
